import { defineConfig, devices } from "@playwright/test";
export default defineConfig({
  testDir: "./e2e",
  fullyParallel: false,
  workers: 1,
  use: { baseURL: "http://127.0.0.1:18080", trace: "retain-on-failure" },
  projects: [{ name: "chromium", use: { ...devices["Desktop Chrome"] } }],
  webServer: {
    command: "cargo run --locked --manifest-path ../Cargo.toml -p larkai",
    url: "http://127.0.0.1:18080/healthz",
    reuseExistingServer: false,
    timeout: 120000,
    env: {
      HOST: "127.0.0.1",
      PORT: "18080",
      DATABASE_PATH: ":memory:",
      FRONTEND_DIST: "dist",
      FEISHU_MODE: "mock",
      OIDC_ISSUER: "",
      OIDC_CLIENT_ID: "",
      OIDC_CLIENT_SECRET: "",
      PUBLIC_ORIGIN: "",
      CF_ACCESS_ISSUER: "",
      CF_ACCESS_AUD: "",
      RM_AUTO_COLLECT_SECONDS: "0",
      SMTP_HOST: "",
      NOTIFY_ON_TASK_CHANGE: "0",
    },
  },
});
